#version 450
#extension GL_EXT_shader_atomic_float : require

layout(binding = 0) uniform sampler2DArray uBaryTex;
layout(std430, binding = 1) readonly buffer VertexList {
    uint vertexList[];
};
layout(std430, binding = 2) buffer LambdaOut {
    float lambda[];
};
layout(std430, binding = 3) buffer WSumOut {
    float wsum[];
};
layout(binding = 4) uniform sampler2DArray uSolidAngleTex;
layout(binding = 5) uniform sampler2DArray uDepthTex;

layout(push_constant) uniform Params {
    ivec2 uFaceSize;
    int   uNumPrimitives;
    int   uVerticesPerPrimitive;
} params;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main()
{
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;
    uint face = gl_GlobalInvocationID.z;

    if (x >= uint(params.uFaceSize.x) || y >= uint(params.uFaceSize.y) || face >= 6u)
    {
        return;
    }

    vec4 tex = texelFetch(uBaryTex, ivec3(x, y, face), 0);
    vec4 depthTex = texelFetch(uDepthTex, ivec3(x, y, face), 0);
    uint primitive = uint(depthTex.a * float(params.uNumPrimitives) + 0.5);
    if (primitive >= uint(params.uNumPrimitives))
    {
        return;
    }

    float w = texelFetch(uSolidAngleTex, ivec3(x, y, face), 0).r;
    uint base = primitive * uint(params.uVerticesPerPrimitive);

    atomicAdd(lambda[vertexList[base + 0u]], tex.r * w);
    atomicAdd(lambda[vertexList[base + 1u]], tex.g * w);
    atomicAdd(lambda[vertexList[base + 2u]], tex.b * w);
    if (params.uVerticesPerPrimitive == 4)
    {
        atomicAdd(lambda[vertexList[base + 3u]], tex.a * w);
    }

    atomicAdd(wsum[0], w);
}
