#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 1, scalar) buffer Vertices {
    vec4 vertices[];
};

layout(set = 0, binding = 2, scalar) buffer RayDirections {
    vec4 directions[];
};

layout(push_constant) uniform PushConstants {
    uint vertexCount;
    uint raysPerVertex;
    uint maxHitsPerRay;
} pc;

layout(location = 0) rayPayloadEXT uint payload;

void main()
{
    uint rayIndex =  gl_LaunchIDEXT.x +
    gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x +
    gl_LaunchIDEXT.z * gl_LaunchSizeEXT.x * gl_LaunchSizeEXT.y;

    uint vertexIndex = rayIndex / pc.raysPerVertex;

    if (vertexIndex >= pc.vertexCount)
        return;

    vec3 origin = vertices[vertexIndex].xyz;
    vec3 dir    = normalize(directions[rayIndex].xyz);

    payload = rayIndex;
    if (rayIndex == 0)
    payload = 999999;

    traceRayEXT(
        tlas,
        gl_RayFlagsOpaqueEXT,
        0xFF,
        0, 0, 0,
        origin,
        0.001,
        dir,
        10000.0,
        0
    );
}